### ISSUE TITLE
<PENTASIA>Incorrect logo displayed for PENTASIA company

### ISSUE THREAD

**Issue by AnaLazar** [peviitor-ro/issues#155]
ENVIRONMENT: https://firme.peviitor.ro/

URL: https://firme.peviitor.ro/

browser: Google Chrome Version 114.0.5735.199

STEPS TO REPRODUCE:

1. Access the link (https://firme.peviitor.ro/) on your browser
2. Type "PENTASIA" in the search bar
3. Press enter
4. Observe the logo displayed on the home page

EXPECTED RESULTS:
The correct company logo should be displayed.

![pentasia logo](https://github.com/peviitor-ro/issues/assets/129599381/ca3b2a29-0380-4773-ae97-1a98f66ec660)

ACTUAL RESULTS:
The logo displayed is incorrect and does not match the company's branding.

![wrong pentasia logo](https://github.com/peviitor-ro/issues/assets/129599381/9342160b-97e5-4455-992c-71480e674f56)

**Comment by Codetamer333** [comment]
Rezolvat ieri, logo corect se afiseaza
