### ISSUE TITLE
<PENTASIA>Incorrect number of jobs listed

### ISSUE THREAD

**Issue by AnaLazar** [peviitor-ro/issues#156]
ENVIRONMENT: https://firme.peviitor.ro/

URL: https://firme.peviitor.ro/

browser: Google Chrome Version 114.0.5735.199

STEPS TO REPRODUCE:

1.Access the link (https://firme.peviitor.ro/) on your browser
2.Type "PENTASIA" in the search bar
3.Press enter
4.Check results
ACTUAL RESULT:
A no of 14 vacancies located in Romania is shown on the website page.
![jobs listed on pe viitor](https://github.com/peviitor-ro/issues/assets/129599381/5a2c69bd-4ac0-4856-bb8b-ed13a15daf9f)

EXPECTED RESULTS:
A no of 15 vacancies located in Romania should be posted on the website page.
![jobs listed on site](https://github.com/peviitor-ro/issues/assets/129599381/353d90fd-d604-4afd-9764-495f9718a6ea)

**Comment by Codetamer333** [comment]
Reparat azi 21.07 ora 00:05
