### ISSUE TITLE
<ORTEC>Incorrect number of jobs listed on web page

### ISSUE THREAD

**Issue by AnaLazar** [peviitor-ro/issues#157]
ENVIRONMENT: https://firme.peviitor.ro/

URL: https://firme.peviitor.ro/

browser: Google Chrome Version 114.0.5735.199

STEPS TO REPRODUCE:

1.Access the link (https://firme.peviitor.ro/) on your browser
2.Type "ORTEC" in the search bar
3.Press enter
4.Check results

ACTUAL RESULT:
A no of 8 vacancies located in Romania is shown on the website page.
![jobs listed on pe viitor1](https://github.com/peviitor-ro/issues/assets/129599381/04575a7e-63ed-4719-b691-01f7ddd7deb2)

EXPECTED RESULTS:
A no of 10 vacancies located in Romania should be shown on the website page.

**Comment by Codetamer333** [comment]
Reparat azi 21.07, ora 00:05
