### ISSUE TITLE
Company logo's not loading

### ISSUE THREAD

**Issue by thinkinbro** [peviitor-ro/issues#158]
Issue found on nVidia and parexel. 
![image](https://github.com/peviitor-ro/issues/assets/97815419/0093fb63-a978-4842-a0a8-97f9709862c8)
![image](https://github.com/peviitor-ro/issues/assets/97815419/6782187a-55ae-4175-9bde-79cb27c56e10)

**Comment by thinkinbro** [comment]
![image](https://github.com/peviitor-ro/issues/assets/97815419/18fb9209-b21a-4598-9c0e-847127a38b11)
Webasto doesn't show any logo, but it has logo assigned, after hovering the mouse it changes the logo on the default "logo not found"
![image](https://github.com/peviitor-ro/issues/assets/97815419/28c9a738-4cb5-4406-ac9c-8a86f6fc27f7)
![image](https://github.com/peviitor-ro/issues/assets/97815419/9df3b8da-ea98-491e-958a-2c4558b17748)

**Comment by TheMrM** [comment]
Logo for Parexel and Webasto are working fine.
![parexel](https://github.com/peviitor-ro/issues/assets/128375812/dce05a05-e8e7-46ea-8661-90cd4847dea1)
![webasto](https://github.com/peviitor-ro/issues/assets/128375812/23fa3702-4dce-47ca-8a2c-f03c1f0585ef)

#Note For Nvidia we are going to remake the scraper. In the current state is not working.
