### ISSUE TITLE
<ADOBE> Incorrect number of jobs listed on web page

### ISSUE THREAD

**Issue by AnaLazar** [peviitor-ro/issues#159]
ENVIRONMENT: https://firme.peviitor.ro/

URL: https://firme.peviitor.ro/

browser: Google Chrome Version 114.0.5735.199

STEPS TO REPRODUCE:

1.Access the link (https://firme.peviitor.ro/) on your browser
2.Type "ADOBE" in the search bar
3.Press enter
4.Check results

ACTUAL RESULT:
A no of 18 vacancies located in Romania is shown on the website page.
![ADOBE PEVIITOR](https://github.com/peviitor-ro/issues/assets/129599381/7053ef94-4dee-4fdb-a4d4-f2e7af5dc660)

EXPECTED RESULTS:
A no of 17 vacancies located in Romania should be shown on the website page.
![ADOBE OFF SITE](https://github.com/peviitor-ro/issues/assets/129599381/b6087104-b2c0-4049-a7af-a51eb0f69426)

**Comment by Codetamer333** [comment]
Not my scraper
