### ISSUE TITLE
<ADOBE> Search results display job from another company 

### ISSUE THREAD

**Issue by AnaLazar** [peviitor-ro/issues#160]
ENVIRONMENT: https://firme.peviitor.ro/

URL: https://firme.peviitor.ro/

browser: Google Chrome Version 114.0.5735.199

STEPS TO REPRODUCE:

1.Access the link (https://firme.peviitor.ro/) on your browser
2.Type "ADOBE" in the search bar
3.Press enter
4.Vacant jobs are posted
5.Check results

ACTUAL RESULT:
The job "Java Developer for Adobe Experience Manager" appears to be from IBM company, not from ADOBE
![adobe ibm](https://github.com/peviitor-ro/issues/assets/129599381/44e08946-fc69-4b21-a037-67e69aacce94)

EXPECTED RESULTS:
When searching for vacant jobs from ADOBE, search results should display only jobs for ADOBE and not other company.
![ibm](https://github.com/peviitor-ro/issues/assets/129599381/bd0a0b9e-9e40-4acb-a507-7abac3f0035c)

**Comment by Codetamer333** [comment]
Not my scraper
