### ISSUE TITLE
<Chorus> Jobs are posted twice in the search results (15+15)

### ISSUE THREAD

**Issue by GeorgePara** [peviitor-ro/issues#163]
ENVIRONMENT: PROD
 url: https://firme.peviitor.ro/
 browser: Chrome

STEPS TO REPRODUCE:
 1)open url in the browser
 2)type Chorus in the search bar
 3)check the number of jobs

EXPECTED RESULTS:
 there should be 15 jobs displayed in the search results

ACTUAL RESULTS:
 there are 30 jobs displayed in the search results (each job is posted twice)

**Comment by stefaniavlad** [comment]
All 15 jobs are displayed correctly now:
![image](https://github.com/peviitor-ro/issues/assets/135824216/53f30c1c-fade-4f14-8eb3-b6633ca5039c)

**Comment by stefaniavlad** [comment]
Closing this issue.
