### ISSUE TITLE
<Codezilla> Jobs are posted twice in the search results (6+6)

### ISSUE THREAD

**Issue by GeorgePara** [peviitor-ro/issues#164]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Codezilla in the search bar
3)check the number of jobs

EXPECTED RESULTS:
there should be 6 jobs displayed in the search results

ACTUAL RESULTS:
there are 12 jobs displayed in the search results (each job is posted twice)

![codezillaDoubleTest](https://github.com/peviitor-ro/issues/assets/135150121/1b6f1f64-4f5d-4b0d-8e7f-84c0e587562e)

**Comment by stefaniavlad** [comment]
All jobs for Codezilla seem to be okay now. 6 jobs are displayed and there are no duplicates:
![image](https://github.com/peviitor-ro/issues/assets/135824216/435f06a6-5042-4c3e-af38-5ca44ca51098)
