### ISSUE TITLE
<Engie> half of the job titles are not available anymore/expired

### ISSUE THREAD

**Issue by GeorgePara** [peviitor-ro/issues#166]
ENVIRONMENT: PROD
 url: https://firme.peviitor.ro/
 browser: Chrome

STEPS TO REPRODUCE:
 1)open url in the browser
 2)type Engie in the search bar
 3)check the following links: Diriginte de santier, CHP&Energy Efficiency Solutions Expert, Consultant SAP functional (BW), Electrical Design Engineer(MEP), Structural Engineer with German, Operator GIS junior, Specialist monitorizare business, Planificator activitate distributie, Power Systems Consultant, Business Project Manager,  Road Design Engineer, Product manager, Sourcing Specialist, Inginer

EXPECTED RESULTS:
 there should be 30 job titles with working links

ACTUAL RESULTS:
 15/30 job titles are not available anymore or expired

![engiePgnotfoundBug](https://github.com/peviitor-ro/issues/assets/135150121/35daa19c-0a71-4ef8-93c8-6cfd262aebab)

**Comment by stefaniavlad** [comment]
Searched for Romania on their careers page and found 14 jobs available.
![image](https://github.com/peviitor-ro/issues/assets/135824216/850d75b0-3e32-46ce-a796-654998f3f6a8)
![image](https://github.com/peviitor-ro/issues/assets/135824216/4cae52d4-6679-4775-8274-c4e649c0311e)

Executed the scraper again and 14 jobs were displayed successfully:
![image](https://github.com/peviitor-ro/issues/assets/135824216/b947867f-98a0-4ff8-b1ec-943855ab4efc)
