### ISSUE TITLE
<Gameloft> Jobs are posted twice in the search results (9+9)

### ISSUE THREAD

**Issue by GeorgePara** [peviitor-ro/issues#168]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Gameloft in the search bar
3)check the number of jobs

EXPECTED RESULTS:
there should be 9 jobs displayed in the search results

ACTUAL RESULTS:
there are 18 jobs displayed in the search results (each job is posted twice)

![gameloftDoubleTest](https://github.com/peviitor-ro/issues/assets/135150121/c2be1c0e-18be-4f82-9f39-57c1d3722764)

**Comment by stefaniavlad** [comment]
Executed again the scraper and only 9 jobs are displayed with no duplicates.
![image](https://github.com/peviitor-ro/issues/assets/135824216/66da6912-e06b-4a6c-a2d5-39027dd787f4)
