### ISSUE TITLE
<Seimaf> Jobs are posted twice in the search results (3+3)

### ISSUE THREAD

**Issue by GeorgePara** [peviitor-ro/issues#169]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Seimaf in the search bar
3)check the number of jobs

EXPECTED RESULTS:
there should be 3 jobs displayed in the search results

ACTUAL RESULTS:
there are 6 jobs displayed in the search results (each job is posted twice)

![seimafDoubleTest](https://github.com/peviitor-ro/issues/assets/135150121/67e5cd20-81ee-4c88-810e-eacf53e23ed0)

**Comment by stefaniavlad** [comment]
Executed the scraper again and only 3 jobs are displayed now:
![image](https://github.com/peviitor-ro/issues/assets/135824216/fe2e22e4-c005-497a-9cf5-690a75abe1ce)
