### ISSUE TITLE
<Tradeville> Jobs are posted twice in the search results (11+11)

### ISSUE THREAD

**Issue by GeorgePara** [peviitor-ro/issues#172]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Tradeville in the search bar
3)check the number of jobs

EXPECTED RESULTS:
there should be 11 jobs displayed in the search results

ACTUAL RESULTS:
there are 22 jobs displayed in the search results (each job is posted twice)

![TradevilleDoubleTest](https://github.com/peviitor-ro/issues/assets/135150121/6fa6e02a-25ae-43ab-9a62-3a9980ae9104)

**Comment by stefaniavlad** [comment]
Executed the scraper again and only 11 jobs are displayed now:
![image](https://github.com/peviitor-ro/issues/assets/135824216/df3f9f5f-2289-43cc-9b75-eb7414ba0cd8)
