### ISSUE TITLE
<DEDEMAN> Incorrect number of jobs listed on web page

### ISSUE THREAD

**Issue by AnaLazar** [peviitor-ro/issues#175]
ENVIRONMENT: https://firme.peviitor.ro/

URL: https://firme.peviitor.ro/

browser: Google Chrome Version 114.0.5735.199

STEPS TO REPRODUCE:

1.Access the link (https://firme.peviitor.ro/) on your browser
2.Type "DEDEMAN" in the search bar
3.Press enter
4.Check results

ACTUAL RESULT:
A no of 54 vacancies located in Romania is shown on the website page.
![DEDEMAN](https://github.com/peviitor-ro/issues/assets/129599381/22fd5eb0-11d0-4f46-8aaa-47ef4fc377b8)

EXPECTED RESULTS:
A no of 57 vacancies located in Romania should be shown on the website page.

![DDM](https://github.com/peviitor-ro/issues/assets/129599381/12ad1ba0-a4da-402b-85f0-ae1457330f33)

**Comment by TheMrM** [comment]
As of 12.08.2023 | 01.53 am dedeman.py got 57 jobs. Will mark issue as solved and leave it open if the problem persists.
#NOTE try re-rolling the script if the jobs are not posted correctly
![jobs](https://github.com/peviitor-ro/issues/assets/128375812/fb59456b-bc63-45b3-a7a2-2ef3fab92a45)
