### ISSUE TITLE
JOB EXPIRED - SIGCOMBIBLOCSERVICES - Order Management Senior Analyst with German

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/issues#243]
ENVIRONMENT: PROD
url: https://solr.peviitor.ro
browser: Microsoft Edge

STEPS TO REPRODUCE:
1. Open https://solr.peviitor.ro/
2. Go to  SIGCOMBIBLOCSERVICES - Order Management Senior Analyst with German
3. Check the job on the eJobs website

EXPECTED RESULTS:
The job is valid

ACTUAL RESULTS:
The job has expired

![image](https://github.com/peviitor-ro/issues/assets/122023703/e3957243-4ae4-4b00-9b70-63b8f56ebb3c)

**Comment by TheMrM** [comment]
Removed the expired job from PROD. The company should not show up anymore.

![1](https://github.com/peviitor-ro/issues/assets/128375812/2eed8b3e-eeca-426b-bb9b-d11ec82bc634)
