### ISSUE TITLE
JOB EXPIRED -  DOMENIULPUBLICCIMPIATURZIISA - Inginer Sef in Constructii -  cai ferate, drumuri, poduri

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/issues#244]
ENVIRONMENT: PROD
url: https://solr.peviitor.ro
browser: Microsoft Edge

STEPS TO REPRODUCE:
1. Open https://solr.peviitor.ro/
2. Go to  DOMENIULPUBLICCIMPIATURZIISA - Inginer Sef in Constructii -  cai ferate, drumuri, poduri
3. Check the job on the eJobs website

EXPECTED RESULTS:
The job is valid

ACTUAL RESULTS:
The job has expired

![image](https://github.com/peviitor-ro/issues/assets/122023703/4de3e6b2-782e-4542-a024-ba0ef71df2bb)

**Comment by TheMrM** [comment]
Removed the expired job from PROD. The company should not show up anymore.

![1](https://github.com/peviitor-ro/issues/assets/128375812/88b0c341-9bea-43b4-898e-60e24a5aee07)
