### ISSUE TITLE
JOB EXPIRED - ASTROIKODOMI - Muncitor in constructii

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/issues#245]
ENVIRONMENT: PROD
url: https://solr.peviitor.ro
browser: Microsoft Edge

STEPS TO REPRODUCE:
1. Open https://solr.peviitor.ro/
2. Go to  ASTROIKODOMI - Muncitor in constructii
3. Check the job on the eJobs website

EXPECTED RESULTS:
The job is valid

ACTUAL RESULTS:
The job has expired

![image](https://github.com/peviitor-ro/issues/assets/122023703/b41f4234-fafc-4717-a5da-ded200dabbc9)

**Comment by TheMrM** [comment]
Removed the expired job from PROD. The company
![1](https://github.com/peviitor-ro/issues/assets/128375812/c1325602-ef91-44a7-a3f2-61c7adfbcc23)
 should not show up anymore.
