### ISSUE TITLE
JOB EXPIRED - PRIMOFINANCEFINTEC - Agent vanzari callcenter

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/issues#246]
ENVIRONMENT: PROD
url: https://solr.peviitor.ro/
browser: Microsoft Edge

STEPS TO REPRODUCE:

1. Open https://solr.peviitor.ro/
2. Go to  PRIMOFINANCEFINTEC - Agent vanzari callcenter
3. Check check the validity of the job on the eJobs website

EXPECTED RESULTS:
The job is valid

ACTUAL RESULTS:
The job has expired

![image](https://github.com/peviitor-ro/issues/assets/122023703/430b8ac8-fdce-4cf0-a9ad-e04ac64bd238)

**Comment by TheMrM** [comment]
Removed the expired job from PROD. The company should not show up anymore.

![1](https://github.com/peviitor-ro/issues/assets/128375812/4b208cbd-f646-41d6-b828-fe6459d61c40)
