### ISSUE TITLE
Missing logo -Signifytechnology

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#250]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Yonder in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Signifytechnology should be displayed correctly

ACTUAL RESULTS:
Signifytechnology logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo
![bug ](https://github.com/peviitor-ro/issues/assets/123496277/e20cb1f8-7663-4576-89f6-66a6ba261175)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/64f568bc-681f-425d-bcc3-e4d7c63f726f)
Logo appears now.
