### ISSUE TITLE
Missing logo - Harman

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#251]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Harman in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Harman should be displayed correctly

ACTUAL RESULTS:
Harman logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo
![Screenshot_7](https://github.com/peviitor-ro/issues/assets/124587607/b6055497-32f3-4dbd-932f-f9f966b9ff03)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/4f7fb8f4-ff02-4790-87cf-a25cf9178449)
Logo appears now.

**Comment by LarisaM16** [comment]
Logo disappear again.

![Screenshot_16](https://github.com/peviitor-ro/issues/assets/124587607/74a7f7af-a3a1-4695-9955-184896f7855e)

**Comment by LarisaM16** [comment]
Now looks fine. I closed it!


![Image](https://github.com/peviitor-ro/issues/assets/124587607/c2e23273-78b1-4fc5-b88e-9c0cd16f5b47)
