### ISSUE TITLE
Missing logo - LucaNet

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#252]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type LucaNet in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for LucaNet should be displayed correctly

ACTUAL RESULTS:
LucaNet logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo

**Comment by GabyRP06** [comment]
![Screenshot 2023-09-25 202524](https://github.com/peviitor-ro/issues/assets/123496277/e0925d60-bb54-4924-ac51-1b3db6cef2e1)

**Comment by melania23m** [comment]
Logo appears now.
![image](https://github.com/peviitor-ro/issues/assets/112417484/e1a43d68-85f2-4d6f-b1a1-b91840fe6e23)
