### ISSUE TITLE
Missing logo Smartree

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#253]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Smartree in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Smartree should be displayed correctly

ACTUAL RESULTS:
Smartree 
![bug Smartree](https://github.com/peviitor-ro/issues/assets/123496277/78728ab8-9292-44a0-a4f4-ac14b7fd6a52)
logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/947d0f70-05b7-4743-b843-612edb435406)
