### ISSUE TITLE
Missing logo - AtekSoftware

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#254]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type AtekSoftware in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for AtekSoftware should be displayed correctly

ACTUAL RESULTS:
AtekSoftware 
![AtekSoftware](https://github.com/peviitor-ro/issues/assets/123496277/5f368579-8ed4-4f83-afdc-1d1871233980)
logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/37f260fd-a6ed-496c-ab7a-ed28a07748f1)
