### ISSUE TITLE
Missing logo - REI

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#255]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type REI in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for REI should be displayed correctly

ACTUAL RESULTS:
REI 
![REI](https://github.com/peviitor-ro/issues/assets/123496277/71442e02-9ddb-4466-a68f-1e1af6e051bf)
logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo

**Comment by melania23m** [comment]
Logo seems to be okay now.
![image](https://github.com/peviitor-ro/issues/assets/112417484/1f57f2c2-b6c6-49ed-884b-f61750c4523b)
