### ISSUE TITLE
Incorrect  jobs number - Worldline

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#274]
ENVIRONMENT: PROD
url: https://peviitor.ro/ 
browser: Chrome/ FireFox/ Microsoft Edge

STEPS TO REPRODUCE:
1)open url in the browser
2)type Worldline in the search bar
3)check the jobs number for Romania
4)open URL https://careers.worldline.com/
5)check the jobs number for Romania

EXPECTED RESULTS:
the number of jobs for Worldline should be displayed correctly
ACTUAL RESULTS:
The number of jobs for peviitor.ro does not coincide with the number on the official website
On the peviitor.ro appear 27 jobs while 26 appear on careers.worldline.com
![Screenshot_1](https://github.com/peviitor-ro/issues/assets/124587607/dcef5939-29c5-4c38-9de2-eea817b29ae6)
![Screenshot_2](https://github.com/peviitor-ro/issues/assets/124587607/3fdc0caa-61be-4461-8d0c-38f4b90a100f)

**Comment by melania23m** [comment]
I removed the job from France which was listed on the Romania job page
![image](https://github.com/peviitor-ro/issues/assets/112417484/d225003a-67c5-4957-8fec-47f21d7b7b4b)
