### ISSUE TITLE
Different job location- (Romania instead of France)-Worldline HEAD OF INTERNATIONAL TREASURY - MERCHANT SERVICES (W/M)

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#276]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/worldline/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Worldline in the search bar
3)check the country for the job HEAD OF INTERNATIONAL TREASURY - MERCHANT SERVICES (W/M)

EXPECTED RESULTS:
the country for for the job HEAD OF INTERNATIONAL TREASURY - MERCHANT SERVICES (W/M)  should be displayed correctly

ACTUAL RESULTS:
 
the country Romania is displayed instead of the France

![Screenshot_3](https://github.com/peviitor-ro/issues/assets/124587607/fd5487b4-2994-4d71-8955-fc720b714968)

![Screenshot_4](https://github.com/peviitor-ro/issues/assets/124587607/c70c4a91-f653-4d56-a0e9-fc57f60044c3)

**Comment by melania23m** [comment]
It should appear correctly now.
