### ISSUE TITLE
MISSING LOGO - Welocalize

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#282]
ENVIRONMENT: PROD
URL: https://firme.peviitor.ro/
browser: Chrome/Microsoft Edge

STEPS TO REPRODUCE:
1)open URL in the browser
2)type Welocalize in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Welocalize should be displayed correctly

ACTUAL RESULTS:
Welocalize logo is missing

"LOGO NOT FOUND" is displayed instead of the real logo
![Screenshot_7](https://github.com/peviitor-ro/issues/assets/124587607/ea639e1e-ffb0-45c6-8bef-116aeff8780c)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/00b962e9-fa80-4f39-8868-2a9aa48178d9)

**Comment by LarisaM16** [comment]
Now looks fine. I closed it!


![Image](https://github.com/peviitor-ro/issues/assets/124587607/317c5045-1af1-4052-8430-5cece2340d19)
