### ISSUE TITLE
Missing logo Accessgroup

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#283]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Access in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Access should be displayed correctly

ACTUAL RESULTS:
Access 
![logo access](https://github.com/peviitor-ro/issues/assets/123496277/7ed8273d-8ccc-4cc0-9b38-f250510cd607)
logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo

**Comment by GabyRP06** [comment]
![Accesgroup](https://github.com/peviitor-ro/issues/assets/123496277/f58b3446-ac4f-4163-ace7-e00ec0c18b56)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/92376b6c-49e0-49b9-9ba6-3bbf844ecccc)
it seems to be ok now

**Comment by GabyRP06** [comment]
in this evening seems to be missing again the logo
![aceesgroup logo](https://github.com/peviitor-ro/issues/assets/123496277/683501f3-54d7-416c-a178-0de10517f3fb)

**Comment by GabyRP06** [comment]
I fixed this bug, in this morning the logo seems to be ok.

**Comment by GabyRP06** [comment]
retested: logo, targetare link, careers link, run scraper,nr of jobs, location, , all links are ok.
