### ISSUE TITLE
MISSING LOGO - Raiffeisen Bank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#284]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome/ FireFox

STEPS TO REPRODUCE:
1)open URL in the browser
2)type Raiffeisen Bank in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Raiffeisen Bank should be displayed correctly

ACTUAL RESULTS:
Raiffeisen Bank logo is missing

"LOGO NOT FOUND" is displayed instead of the real logo
![Screenshot_8](https://github.com/peviitor-ro/issues/assets/124587607/4c88d2f9-3f01-4c4f-bb52-6c858ed76eb3)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/a035d206-4d56-41cb-b13b-6a05e0677e5c)
it seems to be ok now

**Comment by LarisaM16** [comment]
I closed it!
