### ISSUE TITLE
Missing logo Acrelec

### ISSUE THREAD

**Issue by GabyRP06** [peviitor-ro/issues#287]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type Acrelec in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Acrelec  should be displayed correctly

ACTUAL RESULTS:
Acrelec logo is missing.
![Acrelec](https://github.com/peviitor-ro/issues/assets/123496277/7b83be8b-9b71-49b6-8a9d-ac0f9bcafc68)

"LOGO NOT FOUND" is displayed instead of the real logo

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/793e44ba-b903-44cd-8d6a-ad29f4f1781a)
please retest.

**Comment by GabyRP06** [comment]
![acrelec logo 03 10](https://github.com/peviitor-ro/issues/assets/123496277/db04dabd-e01c-4390-a741-83d1d10af966)
I don't see the logo
