### ISSUE TITLE
Incorrect jobs number - RaiffeisenBank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#288]
ENVIRONMENT: PROD
url: https://peviitor.ro/
browser: Chrome/ FireFox/ Microsoft Edge

STEPS TO REPRODUCE:
1)open url in the browser
2)type RaiffeisenBank in the search bar
3)check the jobs number for Romania
4)open URL https://www.raiffeisen.ro/despre-noi/cariere/posturi-vacante/#
5)click on the link https://www.ejobs.ro/company/raiffeisen-bank/4779
https://www.linkedin.com/jobs/search/?keywords=raiffeisen
![Screenshot_14](https://github.com/peviitor-ro/issues/assets/124587607/64e8cf4d-8a5c-46f1-a149-ba69985fb793)

6)check the jobs number for Romania

EXPECTED RESULTS:
the number of jobs for RaiffeisenBank should be displayed correctly
ACTUAL RESULTS:
The number of jobs for peviitor.ro does not coincide with the number on the official website RaiffeisenBank
On the peviitor.ro appear 22 jobs while 28 appear on  (https://www.ejobs.ro/company/raiffeisen/4779) and 30 on https://www.linkedin.com/jobs/search/?keywords=raiffeisen
![Screenshot_12](https://github.com/peviitor-ro/issues/assets/124587607/487c112e-8de4-4af2-abc8-d672cb5ee1f9)

![Screenshot_13](https://github.com/peviitor-ro/issues/assets/124587607/13e140ee-d30c-42f4-ad6e-a3d6f8d74e79)

![Screenshot_15](https://github.com/peviitor-ro/issues/assets/124587607/0cf34a70-ed5d-43db-a85e-a4856141f85c)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/86795a5d-3e07-4bc0-a46c-59796f3d89b1)
RaiffaisenBank has the jobs posted on ejobs and linkedin. Usually the jobs are repeated and I preferred to take them only from ejobs.

**Comment by LarisaM16** [comment]
Still appear 23 jobs on peviitor.ro
![Screenshot_21](https://github.com/peviitor-ro/issues/assets/124587607/85ce5fab-282b-4b95-8b02-94312c9acbda)
On ejobs are 29.

**Comment by melania23m** [comment]
true. Ejobs update the jobs quite often. We update once a day. I updated manually, and now it seems to be okey.
![image](https://github.com/peviitor-ro/issues/assets/112417484/bd70e4da-d611-4434-8f16-f6b1206585e0)
