### ISSUE TITLE
Incorrect jobs number - Bnp Paribas

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#290]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome/ FireFox/ Microsoft Edge

STEPS TO REPRODUCE:
1)open URL in the browser
2)type Bnpparibas in the search bar
3)check the jobs number for Romania
4)open URL https://www.romania.bnpparibas.com/en/join-us/page/3/
5)check the jobs number for Romania

EXPECTED RESULTS:
the number of jobs for Worldline should be displayed correctly
ACTUAL RESULTS:
The number of jobs for peviitor.ro does not coincide with the number on the official website
On the peviitor.ro appear 29 jobs while 30 appear on Bnpparibas

![Screenshot_17](https://github.com/peviitor-ro/issues/assets/124587607/21567464-5f61-4b81-9dec-8734015a0122)
![Screenshot_18](https://github.com/peviitor-ro/issues/assets/124587607/6a88cd45-aef3-4da5-a9fa-d06e876ff944)

**Comment by melania23m** [comment]
I extracted the data from their all-the -world jobs URL. https://group.bnpparibas/en/careers/all-job-offers/roumanie?page=1
![image](https://github.com/peviitor-ro/issues/assets/112417484/793daf26-b89b-4fe4-b62f-e67119693da5)

**Comment by LarisaM16** [comment]
From this link https://group.bnpparibas/en/careers/all-job-offers/roumanie?page=1 appear
 
![Screenshot_20](https://github.com/peviitor-ro/issues/assets/124587607/3b167d82-fa47-488e-a03c-3f01510e7e58)

**Comment by LarisaM16** [comment]
It has now been updated according to the information. I closed the bug.
