### ISSUE TITLE
Peviitor.ro does not have the same number of jobs as Harman Careers

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#298]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome/ FireFox/ Microsoft Edge

STEPS TO REPRODUCE:
1)open URL in the browser
2)type Harman in the search bar
3)check the jobs number for Romania
4)open URL https://harman.wd3.myworkdayjobs.com/ro-RO/HARMAN?locationCountry=f2e609fe92974a55a05fc1cdc2852122
5)check the jobs number for Romania

EXPECTED RESULTS:
the number of jobs for Harman should be displayed correctly
ACTUAL RESULTS:
The number of jobs for peviitor.ro does not coincide with the number on the Harman Careers
On the peviitor.ro appear 15  jobs while 19 appear on Harman Careers

 
![Screenshot_36](https://github.com/peviitor-ro/issues/assets/124587607/1cdcc1ae-abd4-4747-b23d-04668be3fc3c)

![Screenshot_35](https://github.com/peviitor-ro/issues/assets/124587607/fe6c79ac-3ebc-439c-84a1-4700587d4809)

![Screenshot_37](https://github.com/peviitor-ro/issues/assets/124587607/163ad460-bcc2-4234-8203-abce9ca513f6)

**Comment by melania23m** [comment]
On https://www.harman.com/ website, click on "Careers" then the "Search" button next to "Join the HARMAN team / Search for open positions" with blue font. 
The button redirects you to https://harmanglobal.avature.net/careers website. This is the URL where the scraper extracts the data from.
