### ISSUE TITLE
Different job location (Romania instead of București, Cluj-Napoca) - Responsabil Creditare Microbusiness si IMM RaiffeisenBank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#305]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser
Go to Raiffeisen Bank - Responsabil Creditare Microbusiness si IMM RaiffeisenBank
Check the Job location
Open https://www.ejobs.ro/user/locuri-de-munca/responsabil-creditare-microbusiness-si-imm/1707984
Check the job location
EXPECTED RESULTS:
The job location is București, Cluj-Napoca like on the Raiffeisen Bank website
![Screenshot_44](https://github.com/peviitor-ro/issues/assets/124587607/aecc7ba8-86f9-4e67-8b6a-dc18dc111c0c)

ACTUAL RESULTS:
The job location is Romania

![Screenshot_45](https://github.com/peviitor-ro/issues/assets/124587607/3c329403-b64e-49f6-bbda-c93b845899e8)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/34b6cf26-8a9f-4a6a-9c39-3862c0c0a02c)
Fixed. Please retest.
