### ISSUE TITLE
Different job location (Romania- Romania instead of Cluj-Napoca, Deva) - Consilier Creditare PF  Raiffeisen Bank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#306]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to Raiffeisen Bank - Consilier Creditare PF 
3. Check the Job location
4. Open https://www.ejobs.ro/user/locuri-de-munca/consilier-creditare-pf/1708317
5. Check the job location

EXPECTED RESULTS:
The job location is Cluj-Napoca, Deva like on the Raiffeisen Bank website
![Screenshot_46](https://github.com/peviitor-ro/issues/assets/124587607/2d796314-9d5c-4746-97cf-b1b91fb2687d)

ACTUAL RESULTS:
The job location is Romania

![Screenshot_47](https://github.com/peviitor-ro/issues/assets/124587607/13a10b3b-80fd-4fec-bb5d-b0d565c86f16)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/46770989-5e34-448d-b4f3-93c0c2f35d96)
Fixed. Please retest
