### ISSUE TITLE
Different job location Brașov , Romania instead of Brasov, Dambovita) - Specialist Creditare PF si consiliere IMM RaiffeisenBank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#308]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to Raiffeisen Bank - Specialist Creditare PF si consiliere IMM Raiffeisen Bank
3. Check the Job location
4. Open https://www.ejobs.ro/user/locuri-de-munca/specialist-creditare-pf-si-consiliere-imm/1704289
5. Check the job location

EXPECTED RESULTS:
The job location is Brasov, Dambovita like on the Raiffeisen Bank website
![Screenshot_50](https://github.com/peviitor-ro/issues/assets/124587607/f5820c82-2977-4829-a980-f83ab655f4d9)

ACTUAL RESULTS:
The job location is Brașov , Romania

![Screenshot_51](https://github.com/peviitor-ro/issues/assets/124587607/ed3f3208-a19f-4424-8017-a1e58336207d)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/947e14e7-572e-407e-a593-a3eb769766c0)
Fixed. Please retest
