### ISSUE TITLE
Different job location (Romania , Romania instead of Cluj, Timis ) -Consilier Creditare PF  Raiffeisen Bank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#309]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser
Go to Raiffeisen Bank - Consilier Creditare PF   Raiffeisen Bank
Check the Job location
Open https://www.ejobs.ro/user/locuri-de-munca/consilier-creditare-pf/1704288
Check the job location
EXPECTED RESULTS:
The job location is Cluj, Timis  like on the Raiffeisen Bank website
 
![Screenshot_52](https://github.com/peviitor-ro/issues/assets/124587607/7155f0c2-2592-458d-b99c-8f3f7956bacd)

ACTUAL RESULTS:
The job location is Romania- Romania

 
![Screenshot_53](https://github.com/peviitor-ro/issues/assets/124587607/465ee5dc-61ea-4307-9acb-f8a71e6a16ec)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/ec39534f-0c4f-4dbe-8f02-9287bd06e4ce)
![image](https://github.com/peviitor-ro/issues/assets/112417484/fbdcf2f0-b0c7-4539-a077-92cdcfb52293)

This job has the 'Huedin, Deta' for location. I can't scrape the second location from the detail job page.
