### ISSUE TITLE
Different job location (Romania , Romania instead of Bacau, Botosani, Dambovita, Satu-Mare ) - Consilier Creditare PF Raiffeisen Bank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#310]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser
Go to Raiffeisen Bank -  Consilier Creditare PF Raiffeisen Bank
Check the Job location
Open https://www.ejobs.ro/user/locuri-de-munca/consilier-creditare-pf/1704286
Check the job location
EXPECTED RESULTS:
The job location is Bacau, Botosani, Dambovita, Satu-Mare  like on the Raiffeisen Bank website
![Screenshot_54](https://github.com/peviitor-ro/issues/assets/124587607/144c5fcd-03e6-4e1b-b901-4f1315d17642)

ACTUAL RESULTS:
The job location is Romania
![Screenshot_55](https://github.com/peviitor-ro/issues/assets/124587607/2426ae5d-91e8-469c-8774-83d1eb02832e)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/ab3a6182-783e-4f7d-9606-dd820df70640)
Fixed. Please retest.
