### ISSUE TITLE
Different job location (București , Romania instead of București, Cluj ) - Expert Creditare PF și Mid-Market Raiffeisen Bank 

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#312]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser
Go to Raiffeisen Bank - Expert Creditare PF și Mid-Market Raiffeisen Bank
Check the Job location
Open https://www.ejobs.ro/user/locuri-de-munca/expert-creditare-pf-si-mid-market/1703680
Check the job location
EXPECTED RESULTS:
The job location is București, Cluj  like on the Raiffeisen Bank website
![Screenshot_58](https://github.com/peviitor-ro/issues/assets/124587607/e2b01c64-c7db-4550-a9d2-e8f2f849dba5)

ACTUAL RESULTS:
The job location is Bucuresti, Romania

![Screenshot_59](https://github.com/peviitor-ro/issues/assets/124587607/535e0fe7-8d63-4982-9bc4-dfbcd78e1b65)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/3be6ca3b-7957-46c2-ab73-059f67c13060)
Fixed. Please retest
