### ISSUE TITLE
Different job location (Romania instead of Bacau, Constanta) - Consilier Creditare PF - Constanta, Bacau  RaiffeisenBank

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#313]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/raiffeisenbank/
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

1. Go to Raiffeisen Bank - Consilier Creditare PF - Constanta, Bacau Raiffeisen Bank
2. Check the Job location
3. Open https://www.ejobs.ro/user/locuri-de-munca/consilier-creditare-pf-constanta-bacau/1702388
4. Check the job location

EXPECTED RESULTS:
The job location is Bacau, Constanta like on the Raiffeisen Bank website
 
![Screenshot_60](https://github.com/peviitor-ro/issues/assets/124587607/a0687552-8934-48ec-bded-cfd532fd498d)

ACTUAL RESULTS:
The job location is Romania- Romania

 
 
![Screenshot_61](https://github.com/peviitor-ro/issues/assets/124587607/0bf6c6f9-f4fe-4c6d-9762-4cf9e2719ef7)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/58583501-8c3c-4a49-8772-d50ca1201cf9)
Fixed. Please retest

**Comment by LarisaM16** [comment]
I reset it. Looks fine now.
