### ISSUE TITLE
Different job location (Bacău , Romania instead of Bacău, București, Timișoara) - Responsabil lucrare Electromontaj

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#315]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/electromontaj/#
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

1. Go to Electromontaj - Responsabil Lucrare Electromontaj
2. Check the Job location
3. Open https://electromontaj.ro/responsabil-lucrare/
4. Check the job location

EXPECTED RESULTS:
The job location is Bacău. București, Timișoara like on the Electromontaj website
 
![Screenshot_66](https://github.com/peviitor-ro/issues/assets/124587607/dff5d188-bf00-41fe-b8ca-5a892dcc52b4)

ACTUAL RESULTS:
The job location is Bacău , Romania 

![Screenshot_67](https://github.com/peviitor-ro/issues/assets/124587607/ba0ae971-de24-4326-ab5a-cec7b88b6580)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/53e2d511-01c0-4d48-827e-c928bdb78617)
Fixed
