### ISSUE TITLE
Different job location (Bucuresti , Romania instead of București și Constanța) - Automacaragiu  Electromontaj

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#316]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/electromontaj/#
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

1. Go to Electromontaj - Automacaragiu Electromontaj
2. Check the Job location
3. Open https://electromontaj.ro/automacaragiu/
4. Check the job location

EXPECTED RESULTS:
The job location is București și Constanța like on the Electromontaj website
![Screenshot_68](https://github.com/peviitor-ro/issues/assets/124587607/782f87c4-0051-43e8-bc20-b5999ab08cf2)

ACTUAL RESULTS:
The job location is București -Romania

![Screenshot_69](https://github.com/peviitor-ro/issues/assets/124587607/5ebd37bf-bbc9-459b-9461-efbbebb8ef09)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/3731b431-50df-41a2-a46a-71c4ebf7d27c)
Fixed

**Comment by LarisaM16** [comment]
fixed. I closed it
