### ISSUE TITLE
Different job location (Bucuresti, Romania instead of București, Constanța) - Buldoexcavatorist Electromontaj

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#317]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/electromontaj/#
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

1. Go to Electromontaj -  Buldoexcavatorist Electromontaj
2. Check the Job location
3. Open https://electromontaj.ro/buldoexcavatorist/
4. Check the job location

EXPECTED RESULTS:
The job location is București și Constanța like on the Electromontaj website
 
![Screenshot_70](https://github.com/peviitor-ro/issues/assets/124587607/f75782cf-41fd-4669-9cc8-fd6ba63fd933)

ACTUAL RESULTS:
The job location is București -Romania

 
![Screenshot_71](https://github.com/peviitor-ro/issues/assets/124587607/ab6d5fac-13ee-4221-b6af-a285d057fa88)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/71ed7be1-c366-463e-94a8-43bfc7a7d433)
Fixed
