### ISSUE TITLE
 Job country on Peviitor.ro is Finlanda instead of Romania -  Electromontaj Deservent Utilaje

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#318]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/electromontaj/#
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

1. Go to Electromontaj - Deservent Utilaje Electromontaj
2. Check the Job location
3. Open https://electromontaj.ro/deservent-utilaje/
4. Check the job location

EXPECTED RESULTS:
The job location on peviitor.ro is Romania 

 
ACTUAL RESULTS:
The job location is Finlanda, Romania

![Screenshot_72](https://github.com/peviitor-ro/issues/assets/124587607/d186a7fa-998c-4903-bf9e-9e9101de8700)
![Screenshot_73](https://github.com/peviitor-ro/issues/assets/124587607/f0651589-5ddd-47fe-b27d-17159db140ce)

**Comment by melania23m** [comment]
Fixed. Please retest

**Comment by LarisaM16** [comment]
I I retested it. Now looks ok. I closed it.
