### ISSUE TITLE
Different job location (București , Romania instead of București, Câmpina) - Lăcătuș Mecanic Întreținere Reparații Electromontaj

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#319]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/electromontaj/#
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

Go to Electromontaj - Lăcătuș Mecanic Întreținere Reparații Electromontaj
Check the Job location
Open https://electromontaj.ro/lacatus-mecanic-intretinere/
Check the job location
EXPECTED RESULTS:
The job location is București, Câmpina like on the Electromontaj website

![Screenshot_74](https://github.com/peviitor-ro/issues/assets/124587607/b96b4962-b91a-4450-a747-d7c5c6f01a22)

ACTUAL RESULTS:
The job location is București -Romania
![Screenshot_75](https://github.com/peviitor-ro/issues/assets/124587607/8a0d28d7-5ca1-4ca6-b8b5-7c91a7dc9cfc)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/e3099568-e513-42a0-98b0-571e200fc50d)
Fixed
