### ISSUE TITLE
Different job location (Bucuresti , Romania instead of  București, Pitești, Craiova, Bacău) -Muncitor Necalificat Electromontaj

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#320]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/electromontaj/#
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

Open the URL in the browser

1. Go to Electromontaj - Muncitor Necalificat Electromontaj
2. Check the Job location
3. Open https://electromontaj.ro/muncitor-necalificat/
4. Check the job location

EXPECTED RESULTS:
The job location is  București, Pitești, Craiova, Bacău like on the Electromontaj website

 
![Screenshot_77](https://github.com/peviitor-ro/issues/assets/124587607/f42fc04d-a87d-48a5-8fc4-198c6878464e)

ACTUAL RESULTS:
The job location is București -Romania
 
![Screenshot_78](https://github.com/peviitor-ro/issues/assets/124587607/ce565dbd-b36b-42e6-8d10-ea35b15ed7b5)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/5f7afb6b-daf4-4957-ab4c-12b26e04c0c3)
Fixed

**Comment by LarisaM16** [comment]
looks fine now.
