### ISSUE TITLE
Missing Logo - Electromontaj

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#322]
ENVIRONMENT: PROD
url: https://firme.peviitor.ro/
browser: Chrome/ FireFox

STEPS TO REPRODUCE:
1)open url in the browser
2)type Electromontaj in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Electromontaj should be displayed correctly

ACTUAL RESULTS:
Electromontaj  logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo
![Screenshot_81](https://github.com/peviitor-ro/issues/assets/124587607/cf98dc86-1d69-471b-8235-24bbdffaaaf5)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/ffb31a7e-9142-4406-88d3-2a794279e97b)
:)
out of nowhere

**Comment by LarisaM16** [comment]
now is fixed.
