### ISSUE TITLE
Different job location (No city , Romania  instead of Remote) - Webmarc- Front End Developer

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#323]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro/src/webmarc/
Browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to Webmarc - Front End Developer
3. Check the Job location
4. Open https://webmarc.io/hiring
5. Check the job location

EXPECTED RESULTS:
The job location is Remote like on the Webmarc website

![Screenshot_82](https://github.com/peviitor-ro/issues/assets/124587607/0c96f13e-c447-4063-a8f5-3ad9aff93d78)

ACTUAL RESULTS:
The job location is No city , Romania 
 
![Screenshot_83](https://github.com/peviitor-ro/issues/assets/124587607/d54797ca-80ed-4e5a-86fb-53f7f1711632)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/7b6e188a-47e5-470f-b721-1a27a7f5ae65)
I think that is something wrong with scrapers UI when there is only "remote" key. I have no "city" at all because it is only "remote".

**Comment by LarisaM16** [comment]
Now looks ok!

![Image](https://github.com/peviitor-ro/issues/assets/124587607/d8003418-fe09-428c-b0d4-c895008d9fd1)
