### ISSUE TITLE
MISSING LOGO - Smartree

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#324]
ENVIRONMENT: PROD
URL: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open URL in the browser
2)type Smartree in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Smartree should be displayed correctly

ACTUAL RESULTS:
Smartree logo is missing
"LOGO NOT FOUND" is displayed instead of the real logo
![Screenshot_84](https://github.com/peviitor-ro/issues/assets/124587607/41596119-358a-4a7f-8419-179a4eceb3cd)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/cff2e158-a40e-4410-9200-13c8d814ee8e)
:)

**Comment by LarisaM16** [comment]
Now looks ok.
