### ISSUE TITLE
No job type instead of Remote for this jobs: Unity Engineer, Unity Engineer, Unity Engineer, Project Based Senior Unreal Engineer and Senior Unreal Engineer

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#333]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/amber/
browser: Chrome

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to AMBER -Unity Engineer, Unity Engineer, Unity Engineer, Project Based Senior Unreal Engineer and Senior Unreal Engineer
3. Check The job type 
4. Open https://jobs.jobvite.com/amberstudiocareers/search?l=Craiova
5. Check the  job type 

EXPECTED RESULTS:
The job type is remote like on the AMBER website

![Screenshot_22](https://github.com/peviitor-ro/issues/assets/124587607/fce644cc-7662-49a9-982f-d38a25e68aa5)

ACTUAL RESULTS:
The job type is `No job type`
![Screenshot_19](https://github.com/peviitor-ro/issues/assets/124587607/2cfbbf57-4f9c-4471-b058-7290d88df8c7)
![Screenshot_20](https://github.com/peviitor-ro/issues/assets/124587607/96afd34f-8115-4fe9-a2bf-f2f68b96b840)
![Screenshot_21](https://github.com/peviitor-ro/issues/assets/124587607/1d6582b6-aa70-4980-b739-e28a3089256e)

**Comment by melania23m** [comment]
This job is no longer available, but for the rest of the jobs at AMBER I made the changes
