### ISSUE TITLE
No job type instead Hybrid Remote for Amber - Online Engineer

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#334]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/amber/
browser: Chrome

STEPS TO REPRODUCE:

Open the URL in the browser
Go to AMBER -Online Engineer
Check The job type
Open https://jobs.jobvite.com/amberstudiocareers/search?l=Craiova
Check the job type
EXPECTED RESULTS:
The job type is hybrid  remote like on the AMBER website
 
![Screenshot_23](https://github.com/peviitor-ro/issues/assets/124587607/0c8797b5-68c0-479b-926e-40a8284f9c0e)

ACTUAL RESULTS:
The job type is` No job type`
![Screenshot_24](https://github.com/peviitor-ro/issues/assets/124587607/e2442a6a-b3bf-4e9e-aae8-7f5d5efca79c)

**Comment by melania23m** [comment]
This job is no longer available, but for the rest of the jobs at AMBER I made the changes. It should appear job type now.
![image](https://github.com/peviitor-ro/issues/assets/112417484/7dba72f2-80bb-4a5a-b8cf-a813ad5e3c4a)
