### ISSUE TITLE
No job type instead of Hybrid Remote for this jobs from Amber: Senior Game Designer, Development Services, Accountant, Development Test Specialist,Certification Specialist , VFX Artist,Internal Auditor,Marketing Specialist

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#335]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/amber/
browser: Chrome

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to AMBER -**Senior Game Designer, Development Services, Accountant, Development Test Specialist, Certification Specialist , VFX Artist, Internal Auditor, Marketing Specialist**
3. Check The job type
4. Open  https://jobs.jobvite.com/amberstudiocareers/search?l=Bucharest
5. Check the job type
6. EXPECTED RESULTS:
7. The job type is hybrid remote like on the AMBER website
![Screenshot_25](https://github.com/peviitor-ro/issues/assets/124587607/956dfe28-9a31-4b71-9283-bc272ce7f98b)
![Screenshot_26](https://github.com/peviitor-ro/issues/assets/124587607/3ff03ffe-eba3-4052-9c9c-8ef2bbaeaff2)
![Screenshot_27](https://github.com/peviitor-ro/issues/assets/124587607/572781eb-8bae-4616-8718-0349a672f4fc)
![Screenshot_28](https://github.com/peviitor-ro/issues/assets/124587607/ed3db431-8b52-4700-ade0-9a0fe63cc561)

ACTUAL RESULTS:
The job type is No job type
![Screenshot_29](https://github.com/peviitor-ro/issues/assets/124587607/8a1c62db-5bbd-4a03-b01f-4042d3708689)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/dcdc31db-36a5-4a39-a758-7928e049104a)
Please retest for all amber jobs.
