### ISSUE TITLE
No job type instead of Hybrid Remote for this jobs from Amber: QA Project Manager, Junior Tester, Junior Tester

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#337]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/amber/
browser: Chrome

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to AMBER -QA Project Manager, Junior Tester, Junior Tester
3. Check The job type
4. Open https://jobs.jobvite.com/amberstudiocareers/search?l=Botosani
5. Check the job type

EXPECTED RESULTS:
The job type is hybrid, remote like on the AMBER website
 

ACTUAL RESULTS:
The job type is No job type
 
![Screenshot_31](https://github.com/peviitor-ro/issues/assets/124587607/5a2b65c6-e5a4-4053-9c13-76de1a8c56cf)

**Comment by melania23m** [comment]
Can you retest?
