### ISSUE TITLE
Different job location (Iasi , Romania instead of Iasi, Botosani Romania) - Atek jobs -Java Software Developer, Customer Support Technician,Junior Java Developer

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#338]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/atek/index.html
browser: Chrome
Device: Laptop

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Go to Atek- Java Software Developer, Customer Support Technician, Junior Java Developer
3. Check the Job location
4. Open https://atek.ro/career.html
5. Check the job location

EXPECTED RESULTS:
The job location is Iasi, Botosani - Romania like on the Atek website

![Screenshot_33](https://github.com/peviitor-ro/issues/assets/124587607/1813c7ba-98e8-41dd-9d00-36da179b269e)

ACTUAL RESULTS:
The job location is  Iasi, Romania
![Screenshot_34](https://github.com/peviitor-ro/issues/assets/124587607/4df9f54a-c766-4351-b393-cfee68fff905)

**Comment by melania23m** [comment]
please retest :)

**Comment by LarisaM16** [comment]
![Screenshot_4](https://github.com/peviitor-ro/issues/assets/124587607/6638688b-a799-450e-ba9c-5a1a94e5f481)
after retest

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/eafc9972-f7bb-4cf3-90bb-f426a1423fba)
Please retest.
