### ISSUE TITLE
When I search for AON, it displays the results of another company

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#339]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type AON in the search bar
3)check the name

EXPECTED RESULTS:
AON  is displayed correctly

ACTUAL RESULTS:
The name of the NinjaOne company appears.
![Screenshot_42](https://github.com/peviitor-ro/issues/assets/124587607/d383b05e-8a26-4e5b-adcd-2588120d4b54)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/51bde3d8-9ab1-4eff-81ac-07ae0205e540)
now appears also for AON
