### ISSUE TITLE
Missing Logo - Druid

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#340]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/druid/index.html#
browser: Chrome/ FireFox

STEPS TO REPRODUCE:
1)open url in the browser
2)type Druid in the search bar
3)check the logo

EXPECTED RESULTS:
the logo for Druid should be displayed correctly

ACTUAL RESULTS:
Druid logo is missing
 
![Screenshot_51](https://github.com/peviitor-ro/issues/assets/124587607/c1d90323-3b26-4a4f-a30f-0ae1e6501716)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/1c13add6-5e45-4ffa-a6d1-75a84708ed81)
on peviitor it works. I can't help on scrapersui.

**Comment by LarisaM16** [comment]
click on this link https://scrapers.peviitor.ro/src/druid/index.html#

logo is missing.

**Comment by LarisaM16** [comment]
Now looks fine.
