### ISSUE TITLE
Missing LOGO - Viamedici

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#345]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/viamedici/index.html
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)check the logo

EXPECTED RESULTS:
the logo for Viamedici should be displayed correctly

ACTUAL RESULTS: Viamedici logo is missing
![Screenshot_52](https://github.com/peviitor-ro/issues/assets/124587607/783d23e0-61fc-4474-895d-7ebc3262dbaf)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/dc68e888-a39d-4cdb-a055-f0688bd5483d)

**Comment by LarisaM16** [comment]
enter the mentioned URL. the logo is still missing 
https://scrapers.peviitor.ro/src/viamedici/index.html

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/fe730c9a-f0ed-440c-b95f-b2e61052469c)

**Comment by LarisaM16** [comment]
Looks ok now
