### ISSUE TITLE
Electromontaj -city  location for jobs(Responsabil Lucrare, Automacaragiu, Buldoexcavatorist, Lăcătuș Mecanic Întreținere Reparații,Muncitor Necalificat, Șofer) have  "is not a city in Romania" in descrisption

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/issues#346]
ENVIRONMENT: PROD
URL: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:

1.  open URL in the browser
2.  type Electromontaj  in the search bar
3.  run scraper
4. check city location for this jobs Responsabil Lucrare, Automacaragiu, Buldoexcavatorist, Lăcătuș Mecanic Întreținere Reparații,Muncitor Necalificat, Șofer

EXPECTED RESULTS:
the city is displayed correctly

ACTUAL RESULTS:
 city location have "is not a city in Romania" in description
 
![Screenshot_55](https://github.com/peviitor-ro/issues/assets/124587607/1023ac98-2156-4c51-82be-bad5c0867540)
![Screenshot_56](https://github.com/peviitor-ro/issues/assets/124587607/74eb9f5f-552b-4afa-9366-18ecd21d2864)
![Screenshot_57](https://github.com/peviitor-ro/issues/assets/124587607/0ec0c3d8-72a2-4c0c-a665-643a8ab76865)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/issues/assets/112417484/ce2739fe-2153-48b9-8772-b2ca8252c48a)
Fixed! :)
